# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    db_driver: '%env(resolve:DB_DRIVER)%'
    db_host: '%env(resolve:DB_HOST)%'
    db_user: '%env(resolve:DB_USER)%'
    db_password: '%env(resolve:DB_PASSWORD)%'
    db_port: '%env(resolve:DB_PORT)%'
    db_name: '%env(resolve:DB_NAME)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    Astrocode\:
        resource: '../src/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Astrocode\AppBuilder\Core\Database\Adapter:
        arguments:
            $config:
                driver: '%db_driver%'
                database: '%db_name%'
                hostname: '%db_host%'
                username: '%db_user%'
                password: '%db_password%'
                port: '%db_port%'

